name: test-and-publish
on:
  push:
  pull_request_target:
    types: [opened, synchronize, edited]
  status: {}
jobs:
  build-test-merge-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3.4.0
        with:
          node-version: '14.17'
      - uses: bbeesley/build-test-merge-publish@main
        env:
          GITHUB_TOKEN: ${{ secrets.ATLANTIS_GITHUB_TOKEN }}
  lint-commits:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target') || (github.ref != 'refs/heads/main' && github.event_name == 'push') }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.4.0
      - name: install
        run: npm ci
      - name: commitlint
        run: ./node_modules/.bin/commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
  validate-actions:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target') || (github.ref != 'refs/heads/main' && github.event_name == 'push') }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: nwisbeta/validate-yaml-schema@v2.0.0
        with:
          yamlSchemasJson: |
            {
                "http://json.schemastore.org/github-action": ["action.yml"],
                "https://json.schemastore.org/dependabot-2.0": [".github/dependabot.yml"],
                "http://json.schemastore.org/github-workflow": [".github/workflows/*.yml"]
            }
